### ISSUE TITLE
New Card Design Needed !

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#103]
The current card designs are looking `very low contrast` and very `unorganized`.For a couple of days we were more focused the server side so now it's time to redesign the website starting with a new card design. 

I did some `prototyping `for the new design of the cards . I also added the` color pallets` that i am using for the design here .

![exmaple card](https://user-images.githubusercontent.com/33410545/66711798-9fbdfc80-ed47-11e9-8c0c-b99b7cc34b0f.png) 

If anyone wants to work on it , you're more than welcome :)

Note : 
1) While coding the cards please also keep in mind that `responsiveness `matters .

2) Please follow [these style guidelines](https://github.com/RocktimSaikia/Contribute-101/blob/master/contributors-guide.md) before pushing your changes.

If any additional help or guide needed. I'm here :) 
Happy Coding :computer:

**Comment by LucasOe** [comment]
I would like to work on it!

**Comment by RocktimSaikia** [comment]
@LucasOe  Sure . Please take your time.Don't rush just to put all things together.Also consider what the card should look like if some names are too long.If need any help.You can discuss here !

**Comment by RocktimSaikia** [comment]
hey @LucasOe . This looks okey but i understand with issues that it can be hard to code exactly as the prototype as we dealing with dynamic data so we are not aware of the lengths and how it will affect the look.I tested your code and i came up with another approach that will be good enough for all types of data strings.

![ko](https://user-images.githubusercontent.com/33410545/66716972-b6d10e80-ed88-11e9-864a-564453ae8448.png)

1) The last 3 bars should be used for `tech_stack[0] ,tech_stack[1] ,tech_stack[2] ,` . You can use `display:block` and that should be fine.

2) Add the two social media icons to the left and right corners of the image.It should be `On` the image so that it does not take up any space. You can use various way to achieve this. From `absolute positioning` to `negative spacing`.

Good luck if you get stuck on something please discuss here on this issue, i'm here to help. It's good to take suggestions and help during development rather than after making a complete pull request.

**Comment by LucasOe** [comment]
I've updated the Card Design based on the reference you posted, this is how they currently look:
![image](https://user-images.githubusercontent.com/16548335/66718752-9ab08a00-ede7-11e9-9421-bbdf6c08884c.png)
Only thing I couldn't add is the right line next to the name, if you really want it you might have to add it yourself.
Let me know if I should change anything else.

**Comment by RocktimSaikia** [comment]
@LucasOe That looks pretty good.2nd prototype was successful i guess. Good job . And dont worry about the right line. It was just for me;  when prototyping i like to keep blank spaces filled for my design workflow . You can push it now.If you are done with linting and testing too.

**Comment by LucasOe** [comment]
The changes are already pushed, I think you should be able to merge the Pull Request I made earlier and it's done.
Or should I change the header back? I've only changed the color from a brown to grey, nothing else.

**Comment by RocktimSaikia** [comment]
@LucasOe Good job.Keep an eye for more issues :)
