### ISSUE TITLE
Add a "go top" and "go down" button.

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#164]
Add a "go down" button in the top of the website and onclick it should take you to the bottom of the page and another "go top" button on the bottom which will take you to the top of the page with a simple animation.
For animation no external library is recommended , just use the inbuilt css property `scroll-behavior`.

Anyone wanna take it  is more than welcome !

**Comment by Aravindh-SNR** [comment]
@RocktimSaikia Hi, working on it. Will make a PR soon :)

**Comment by RocktimSaikia** [comment]
@Aravindh-SNR sure go ahead !

**Comment by Aravindh-SNR** [comment]
#165

**Comment by Aravindh-SNR** [comment]
@RocktimSaikia Done! I've used minimal styling for the buttons so that they are in sync with the rest of the page. Hope that's okay.

**Comment by RocktimSaikia** [comment]
@Aravindh-SNR i added some reviews at #165 ; you can make the changes with the provided reviews and push the changes again.I will merged once you done :)

**Comment by Aravindh-SNR** [comment]
@RocktimSaikia I've gone through the reviews and pushed the changes again. Let me know if I should improve anything else. :)

**Comment by RocktimSaikia** [comment]
@Aravindh-SNR Looks good to me :+1: already merged it . good job . Keep an eye for more issues and enhancements .

**Comment by Aravindh-SNR** [comment]
@RocktimSaikia Sure, thanks!
