### ISSUE TITLE
Make the site responsive

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#255]

**Comment by surajat17** [comment]
i am new to open source community.. can i work on this and it would take me a few days like 3-4 to resolve this.

**Comment by RocktimSaikia** [comment]
@surajat17 Sure . Go ahead 👍🏻 . Let me know if you need any type of help

**Comment by Vansh1067** [comment]
Can I work on this and open the PR during Hacktoberfest? :)

**Comment by surajat17** [comment]
@Vansh1067 i am working on it mate:)

**Comment by sushabhardy** [comment]
@RocktimSaikia Please assign the issue to the respective person when finalised, so that others can get to know that issue is already taken.

**Comment by RocktimSaikia** [comment]
@sushabhardy  Yes. I totally forgot about that. Anyway it was recently fixed in #261 by @anushri20 with some of my updated changes on it.
