### ISSUE TITLE
Add a pre commit hook

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#262]
Add a git pre-commit hook for lint checking.
You can use either [Husky](https://github.com/typicode/husky) or [pre-commit](https://github.com/observing/pre-commit) (recommended) for this.

Comment for more information on this one. If you want to contribute but don't understand hooks properly. I'll guide you through.

**Comment by kornfleks** [comment]
Hello,
Does that hook need to fix the linting issues or not ?

**Comment by RocktimSaikia** [comment]
@kornfleks For right now , It should only run the lint error checking script. The developer would have to fix the errors manually if not fixed after running the `npm run lint:fix`
