### ISSUE TITLE
Updating Readme with user-friendly instructions

### ISSUE THREAD

**Issue by IC1101Virgo** [RocktimSaikia/Contribute-101#269]
Updating Readme with new information and making it more beginner-friendly.

**Comment by IC1101Virgo** [comment]
@RocktimSaikia I would like to be given 3-4 days. I hope its no problem. 🦋

**Comment by RocktimSaikia** [comment]
@IC1101Virgo Okey np. Just make sure to submit the pr on the first week of the hacktobestfest.

**Comment by ampsteric** [comment]
I would love to work on this. assign it to me please if not resolved

**Comment by RocktimSaikia** [comment]
@ampsteric  @IC1101Virgo is assigned to this issue at the moment. if it is not resolved within a few days or so then I can assign it to you. But in the meantime then you can look for other issues in the project and work on it.
