### ISSUE TITLE
Make the website responsive 

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#29]
The new updated version of the website is not quite responsive yet . It still shows the website in desktop view even in small screen sizes.Which is not very ideal .

![cdqwwqq](https://user-images.githubusercontent.com/33410545/66419315-c3d0b500-e9b8-11e9-95c4-4a042e2ee175.jpg)

So we have to fix it asap . Anyone willing to work on this issue is more than welcome !
Happy coding :)

**Comment by mikalai-sokarau** [comment]
Hello! I'll take care of it :)

**Comment by RocktimSaikia** [comment]
@mikalai-sokarau  sure :) Let me know if you need any help with the codebase !
