### ISSUE TITLE
Set up webpack for an easy workflow

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#33]
Right now the project has no module bundler .Which makes the development process a bit tedious as you have to restart your server in every single change to see it on the browser.
So i would recommend setting up a very minimal webpack config for the project for now .As the codebase becomes more larger then we will add additional plugins to the config in future.
Right now the most needed plugin is `Hot Module Replacement`.
If anyone wants to take it, you are more than welcome.Or i will set up the webpack very soon myself as this change is very needed .

**Comment by PranjalAgni** [comment]
Can I go for it?

**Comment by RocktimSaikia** [comment]
> Can I go for it?

Sure :) Let me know if you get stuck at any point , I'm here to help . Happy coding !

**Comment by PranjalAgni** [comment]
Just asking why don't we use [nodemon](https://www.npmjs.com/package/nodemon) for `hot-reloading`. It will provide the same live loading feature with zero configuration.

**Comment by RocktimSaikia** [comment]
@PranjalAgni I also thought of using nodemon but nodemon only restarts the server ; It does not refresh the view page on the browser.If you are only working on the server side then nodemon is ok but if you want refresh the page at every changes then we need something like hot reloading.So the new contributors can focus on the frontend side , without having to refresh the browser for every change.

**Comment by RocktimSaikia** [comment]
There are other tools and plugins other than hot reloading for this task for ex. BrowserSync .Which also can be implemented with webpack.

**Comment by PranjalAgni** [comment]
Yup, there is also a tool called [reload](https://www.npmjs.com/package/reload) which automatically reloads your code in browser without any plugins.

**Comment by RocktimSaikia** [comment]
@PranjalAgni That will do too . I was suggesting webpack cause of future scss implementation too but for now you can add this auto reloading feature with any tool that fits in for the project . Once you implement and test it , you can make a pull request and i will review and add it the project asap.

**Comment by PranjalAgni** [comment]
Currently I am working on `webpack` solution I will make a PR as soon as I test it.

**Comment by PranjalAgni** [comment]
I have submitted a PR but getting a weird problem `webpack` is not reloading changes in browser after compiling all the new change.
Also I have added new scripts in `package.json` to run `webpack`

**Comment by PranjalAgni** [comment]
I have fixed the issue now its working fine.

**Comment by RocktimSaikia** [comment]
@PranjalAgni Hi , Webpack config currently works fine.But while testing i realized webpack can get be really hard to get your head around for contributors who are relatively new to server side scene , one single mistake on the config file , the whole app crashes which is not very ideal. So i though of going minimal approach. So i tested various other methods. And settled to go with `reload`. But with the integration with `nodemon` [any monitor module would work like `supervisor` ,`forever` etc] . I tested it and it works like a charm.But i didn't add it to the project yet as you have worked really hard on this issue.So you can make another pull request with my mentioned approach.

I created a boilerplate/guide no how to set nodemon with reload. You can follow these instruction here : 

[https://github.com/RocktimSaikia/hot-reloading-without-webpack](https://github.com/RocktimSaikia/hot-reloading-without-webpack)

**Comment by PranjalAgni** [comment]
Yes @RocktimSaikia I agree with you on how webpack can be a obstacle for newbie developers that's why earlier I suggested `reload` as it will be easy to understand the workflow. Also main thing I realized while working on this issue was we were using `webpack` just because to support live reload and not for any module bundling stuff. 
Second thing I noticed was we didn't need `server.js` after we configured our app with `webpack-dev-server` as after all node server was serving static assets which was taken away by `webpack-dev-server`.
Also it seems `webpack` does not have good support for `ejs-loaders` as it have for other view engines.

**Comment by RocktimSaikia** [comment]
@PranjalAgni Right ! We don't need `server.js` if we integrate `webpack ` at the current state of the project But the reason for setting up the server was for future uses.Lets say when we want to create other routes for our project.Then we will definitely need an active express server for that .But for now yes it just serving static files to the host.

> Second thing I noticed was we didn't need `server.js` after we configured our app with `webpack-dev-server` as after all node server was serving static assets which was taken away by `webpack-dev-server`.

**Comment by PranjalAgni** [comment]
Hey @RocktimSaikia  I have made a new PR check it out.
