### ISSUE TITLE
Link does not open in a new tab.

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#41]
Right now the hyperlinks (github and twitter button) in the website's card does not have `_blank` target , so causing this behavior and not opening the link in a new tab.This is not ideal.
This is a first timers bug. So anyone wants to fix this is more than welcome :)

**Comment by Frozenaught** [comment]
Hey, @RocktimSaikia id like to give this a go if it's ok.

**Comment by RocktimSaikia** [comment]
@Frozenaught  Sure. Go Ahead :)

**Comment by Frozenaught** [comment]
I have submitted a PR I hope this is correct.

**Comment by RocktimSaikia** [comment]
@Frozenaught Great :) Thanks for your contribution :) Keep an eye for more issues
