### ISSUE TITLE
Make the "role" section optional in the UI . (Quick)

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#44]
I have noticed that most of the pull requests now does not include that `role` property.Or may be they forget to include the "role" property when adding their details.And this is causing conflicts in most of the pending pull requests. So we need to make the `role` property optional in the frontend (_not in the backend_) .
One way to solve that is adding `if else`  statement in the `<p>` tag where we are rendering the role property.So the logic should be implemented like this
```
if(role is present)
 render the <p> tag with role the role property.
else
  render a null <p> tag
```

If you are wondering how to implement `if else` in frontend , that's why we are using 'ejs' template engine which supports js implementation in frontend. If you need help. i'm here. 

you will need to implement the logic here : 
[index.ejs](https://github.com/RocktimSaikia/Contribute-101/blob/master/views/index.ejs)

> Till this issue gets resolved no pull requests will get accepted.

**Comment by Phizzard** [comment]
I can take this if it's not taken!

**Comment by RocktimSaikia** [comment]
@Phizzard sure.All yours :)
