### ISSUE TITLE
Fetch github profile and add them to the card .

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/Contribute-101#82]
Right now we have a basic work flow going on .The contributors provide their basic info and we just simply loop through the data and make a card out of it . Along with additional details new contributors also provide their` github username` in the data object.Currently we just use the user_name to add a link to their github profile.But it would be nice if we could also show their `github profile picture` in the card.

This is our current data model which is an `array `of objects :
```
{
name: '',
country: ",
role: '',
tech_stack: ",
github_username: "",
twitter_username: ""
}
```

So what we have to do is to loop through the array of data and fetch the github profile picture using the provided property `github_username` . In a way it is just a fairly simple fetching requirement.

If anyone wants to work on it ,you are more then welcome.
If any help needed i'm here !

Helpful links : 
[https://developer.github.com/v3/users/](https://developer.github.com/v3/users/)

**Comment by unsuitable001** [comment]
I'm working on it :smile:

**Comment by alejandrotoga02** [comment]
@RocktimSaikia  I would like to work it

**Comment by RocktimSaikia** [comment]
@unsuitable001 @alejandrotoga02 Sure go ahead. Btw i forgot to add a special contributors style guide to the project.I'll add an `markdown guide `in a minute please work with that style guide for linting and testing :)

**Comment by unsuitable001** [comment]
@RocktimSaikia can you please tell how to run the app in local env? (I never worked with react/nodeJS). I'm done with editing files. It's time to test :smile:

**Comment by RocktimSaikia** [comment]
@alejandrotoga02 @unsuitable001 Please follow theis style guidelines before making a pull request,

:point_right: **STYLE [GUIDELINE](https://github.com/RocktimSaikia/Contribute-101/blob/master/contributors-guide.md)**
